[project]
name = 'learn_clarity'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.simple-storage]
path = 'contracts/simple-storage.clar'
clarity_version = 3
epoch = '3.2'

[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 3
epoch = '3.2'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'

# 👇 Add this
[networks.devnet]
config_file = "settings/Devnet.toml"